### ISSUE TITLE
redirect url does not work

### ISSUE THREAD

**Issue by robertotacchi72** [finalist/liferay-oidc-plugin#34] opened 2018-10-01 15:59 UTC
Hi 
We have a strange behavior regarding the redirect URL. If the user enter in a private page url (https://mydomainname/private-page)  the OpenID plugin is activated correctly and the Identity Provider login page is shown .  After login the Liferay default login page ( /web/guest/home) is displayed instead of the expected one (/private-page) .
No custom post login hook to redirect to a different page is installed.
The following properties are configured  :
auth.forward.by.last.path=true
auth.forward.by.redirect=true

Thanks

**Comment by gvanderploeg** [comment] 2018-10-02 07:04
Hi,
Thanks for reporting. As from your description I presume this is a dupe of #33 and #31.
I will close this issue and report any progress in one of the other issues instead.

**Closed by gvanderploeg** 2018-10-02 07:04 UTC
Labels: duplicate
